import type { Metadata } from 'next'
import ToolHeader from '@/components/ToolHeader'
import RandomColorWrapper from '@/components/RandomColorWrapper'
import AdBanner from '@/components/AdBanner'
import FAQ from '@/components/FAQ'
import type { FaqItem } from '@/components/FAQ'
import Footer from '@/components/Footer'

export const metadata: Metadata = {
  title: 'Random Color Generator — Generate Random Colors',
  description:
    'Generate random colors instantly with HEX, RGB and HSL values. Free random color generator with palette generation and color history.',
  alternates: { canonical: 'https://randomnumbergenerator.app/random-color' },
  robots: { index: true, follow: true },
}

const faqs: FaqItem[] = [
  {
    q: 'How is a random color generated?',
    a: 'A random color is generated by picking three random values (red, green, blue) each between 0 and 255. The formula is r = Math.floor(Math.random() * 256), and the same for g and b. These three values together define any of the 16.7 million possible RGB colors.',
  },
  {
    q: 'What is a HEX color code?',
    a: 'A HEX color code is a 6-digit hexadecimal representation of a color, preceded by #. Each pair of digits represents the red, green, and blue values (00–FF). For example, #FF0000 is pure red, #00FF00 is green, and #0000FF is blue. HEX codes are widely used in web design and CSS.',
  },
  {
    q: 'What is the difference between RGB and HSL?',
    a: 'RGB (Red, Green, Blue) defines color by mixing three primary light colors. HSL (Hue, Saturation, Lightness) defines color more intuitively: hue is the color type (0–360 degrees on the color wheel), saturation is how vivid it is (0–100%), and lightness is how bright it is (0–100%). HSL is often easier to work with when adjusting colors.',
  },
  {
    q: 'Can I generate a random color palette?',
    a: 'Yes. Click "Generate palette of 5 colors" to create five random colors at once. Each color is shown as a swatch you can click to copy its HEX code. Use this for quickly exploring color combinations for design projects.',
  },
  {
    q: 'How do I use a random color in CSS?',
    a: 'Copy the HEX value (e.g. #A3F2B1) and use it in CSS as background-color: #A3F2B1; or color: #A3F2B1;. You can also use the RGB value directly: background-color: rgb(163, 242, 177); or the HSL value: background-color: hsl(131, 82%, 79%);',
  },
]

const faqSchema = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: faqs.map(f => ({ '@type': 'Question', name: f.q, acceptedAnswer: { '@type': 'Answer', text: f.a } })),
}

const webAppSchema = {
  '@context': 'https://schema.org',
  '@type': 'WebApplication',
  name: 'Random Color Generator',
  url: 'https://randomnumbergenerator.app/random-color',
  description: 'Free random color generator with HEX, RGB, and HSL values, channel locking, palette generation and color history.',
  applicationCategory: 'UtilitiesApplication',
  operatingSystem: 'Any',
  offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
}

const howToSchema = {
  '@context': 'https://schema.org',
  '@type': 'HowTo',
  name: 'How to Generate a Random Color',
  step: [
    { '@type': 'HowToStep', name: 'Click New Color', text: 'Click the "New Color" button or press Space to generate a random color. The large color swatch updates instantly.' },
    { '@type': 'HowToStep', name: 'Copy the color value', text: 'Use the Copy buttons next to HEX, RGB, or HSL to copy the color value in your preferred format to the clipboard.' },
    { '@type': 'HowToStep', name: 'Lock channels or generate a palette', text: 'Lock individual HSL channels (Hue, Saturation, Lightness) to randomize only certain aspects of the color. Or click "Generate palette" for 5 colors at once.' },
  ],
}

const trustSignals = ['🎲 Truly Random', '⚡ Instant', '🔒 Private', '✓ Free']

export default function RandomColorPage() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema).replace(/</g, '\\u003c') }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(webAppSchema).replace(/</g, '\\u003c') }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(howToSchema).replace(/</g, '\\u003c') }} />

      <section className="relative bg-cover bg-center bg-no-repeat" style={{ backgroundImage: "url('/herobgrng.webp')" }}>
        <div className="absolute inset-0 bg-black/60" />
        <div className="relative z-10 pb-10">
          <ToolHeader />
          <div className="text-center text-white px-4 py-8">
            <h1 className="text-3xl sm:text-4xl lg:text-5xl font-bold mb-3 leading-tight">
              Random Color Generator
            </h1>
            <p className="text-lg sm:text-xl text-white/80 mb-6 max-w-2xl mx-auto">
              Generate random colors with HEX, RGB, and HSL values. Lock channels, generate palettes, and browse your color history.
            </p>
            <div className="flex flex-wrap justify-center gap-3 text-sm">
              {trustSignals.map(t => (
                <span key={t} className="bg-white/20 backdrop-blur-sm rounded-full px-4 py-1.5 text-white font-medium">{t}</span>
              ))}
            </div>
          </div>

          <div className="max-w-4xl mx-auto px-4 mb-4">
            <AdBanner slot="8888888888" />
          </div>

          <div className="max-w-2xl mx-auto px-4">
            <div className="bg-white/90 dark:bg-gray-900/90 backdrop-blur-sm shadow-2xl rounded-2xl overflow-hidden">
              <RandomColorWrapper />
            </div>
          </div>
        </div>
        <div className="absolute bottom-0 inset-x-0 h-24 bg-gradient-to-t from-white dark:from-[#0f172a] to-transparent pointer-events-none" />
      </section>

      <section className="bg-white dark:bg-[#0f172a] pt-6">
        <div className="max-w-4xl mx-auto px-4 sm:px-6">
          <div className="pb-4">
            <AdBanner slot="8888888889" />
          </div>

          <div className="rounded-2xl bg-violet-50 dark:bg-violet-950/30 border border-violet-100 dark:border-violet-900/50 px-6 py-5 mb-10">
            <h2 className="text-base font-bold text-violet-900 dark:text-violet-300 mb-2">
              About the random color generator
            </h2>
            <p className="text-sm text-violet-800 dark:text-violet-400 leading-relaxed">
              Our random color generator is a useful tool for designers, developers, and anyone who needs color inspiration. Each color is generated by randomly selecting red, green, and blue values between 0 and 255, giving you access to any of the 16.7 million possible colors. Copy colors in HEX for web design, RGB for programming, or HSL for easier color manipulation. Use the channel locking feature to explore variations — lock the hue to get different shades of the same color, or lock saturation to explore colors with similar vibrancy.
            </p>
          </div>

          <div className="pb-10">
            <FAQ questions={faqs} />
          </div>

          <div className="pb-6">
            <AdBanner slot="8888888880" />
          </div>
        </div>
      </section>

      <Footer />
    </>
  )
}
