import type { Metadata } from 'next'
import ToolHeader from '@/components/ToolHeader'
import RandomColorWrapper from '@/components/RandomColorWrapper'
import AdBanner from '@/components/AdBanner'
import FAQ from '@/components/FAQ'
import type { FaqItem } from '@/components/FAQ'
import Footer from '@/components/Footer'

export const metadata: Metadata = {
  title: 'Random Color Generator — Generate Random Colors',
  description:
    'Generate random colors instantly with HEX, RGB and HSL values. Free random color generator with palette generation and color history.',
  alternates: { canonical: 'https://randomnumbergenerator.app/random-color' },
  robots: { index: true, follow: true },
}

const faqs: FaqItem[] = [
  {
    q: 'How is a random color generated?',
    a: 'A random color is generated by picking three random values (red, green, blue) each between 0 and 255. The formula is r = Math.floor(Math.random() * 256), and the same for g and b. These three values together define any of the 16.7 million possible RGB colors.',
  },
  {
    q: 'What is a HEX color code?',
    a: 'A HEX color code is a 6-digit hexadecimal representation of a color, preceded by #. Each pair of digits represents the red, green, and blue values (00–FF). For example, #FF0000 is pure red, #00FF00 is green, and #0000FF is blue. HEX codes are widely used in web design and CSS.',
  },
  {
    q: 'What is the difference between RGB and HSL?',
    a: 'RGB (Red, Green, Blue) defines color by mixing three primary light colors. HSL (Hue, Saturation, Lightness) defines color more intuitively: hue is the color type (0–360 degrees on the color wheel), saturation is how vivid it is (0–100%), and lightness is how bright it is (0–100%). HSL is often easier to work with when adjusting colors.',
  },
  {
    q: 'Can I generate a random color palette?',
    a: 'Yes. Click "Generate palette of 5 colors" to create five random colors at once. Each color is shown as a swatch you can click to copy its HEX code. Use this for quickly exploring color combinations for design projects.',
  },
  {
    q: 'How do I use a random color in CSS?',
    a: 'Copy the HEX value (e.g. #A3F2B1) and use it in CSS as background-color: #A3F2B1; or color: #A3F2B1;. You can also use the RGB value directly: background-color: rgb(163, 242, 177); or the HSL value: background-color: hsl(131, 82%, 79%);',
  },
]

const faqSchema = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: faqs.map(f => ({ '@type': 'Question', name: f.q, acceptedAnswer: { '@type': 'Answer', text: f.a } })),
}

const webAppSchema = {
  '@context': 'https://schema.org',
  '@type': 'WebApplication',
  name: 'Random Color Generator',
  url: 'https://randomnumbergenerator.app/random-color',
  description: 'Free random color generator with HEX, RGB, and HSL values, channel locking, palette generation and color history.',
  applicationCategory: 'UtilitiesApplication',
  operatingSystem: 'Any',
  offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
}

const howToSchema = {
  '@context': 'https://schema.org',
  '@type': 'HowTo',
  name: 'How to Generate a Random Color',
  step: [
    { '@type': 'HowToStep', name: 'Click New Color', text: 'Click the "New Color" button or press Space to generate a random color. The large color swatch updates instantly.' },
    { '@type': 'HowToStep', name: 'Copy the color value', text: 'Use the Copy buttons next to HEX, RGB, or HSL to copy the color value in your preferred format to the clipboard.' },
    { '@type': 'HowToStep', name: 'Lock channels or generate a palette', text: 'Lock individual HSL channels (Hue, Saturation, Lightness) to randomize only certain aspects of the color. Or click "Generate palette" for 5 colors at once.' },
  ],
}

const trustSignals = ['🎲 Truly Random', '⚡ Instant', '🔒 Private', '✓ Free']

export default function RandomColorPage() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema).replace(/</g, '\\u003c') }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(webAppSchema).replace(/</g, '\\u003c') }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(howToSchema).replace(/</g, '\\u003c') }} />

      <section className="relative bg-cover bg-center bg-no-repeat" style={{ backgroundImage: "url('/herobgrng.webp')" }}>
        <div className="absolute inset-0 bg-black/60" />
        <div className="relative z-10 pb-10">
          <ToolHeader />
          <div className="text-center text-white px-4 py-8">
            <h1 className="text-3xl sm:text-4xl lg:text-5xl font-bold mb-3 leading-tight">
              Random Color Generator
            </h1>
            <p className="text-lg sm:text-xl text-white/80 mb-6 max-w-2xl mx-auto">
              Generate random colors with HEX, RGB, and HSL values. Lock channels, generate palettes, and browse your color history.
            </p>
            <div className="flex flex-wrap justify-center gap-3 text-sm">
              {trustSignals.map(t => (
                <span key={t} className="bg-white/20 backdrop-blur-sm rounded-full px-4 py-1.5 text-white font-medium">{t}</span>
              ))}
            </div>
          </div>

          <div className="max-w-4xl mx-auto px-4 mb-4">
            <AdBanner slot="8888888888" />
          </div>

          <div className="max-w-2xl mx-auto px-4">
            <div className="bg-white/90 dark:bg-gray-900/90 backdrop-blur-sm shadow-2xl rounded-2xl overflow-hidden">
              <RandomColorWrapper />
            </div>
          </div>
        </div>
        <div className="absolute bottom-0 inset-x-0 h-24 bg-gradient-to-t from-white dark:from-[#0f172a] to-transparent pointer-events-none" />
      </section>

      <section className="bg-white dark:bg-[#0f172a] pt-6">
        <div className="max-w-4xl mx-auto px-4 sm:px-6">
          <div className="pb-4">
            <AdBanner slot="8888888889" />
          </div>

          <div className="rounded-2xl bg-violet-50 dark:bg-violet-950/30 border border-violet-100 dark:border-violet-900/50 px-6 py-5 mb-10">
            <h2 className="text-base font-bold text-violet-900 dark:text-violet-300 mb-2">
              About the random color generator
            </h2>
            <p className="text-sm text-violet-800 dark:text-violet-400 leading-relaxed">
              Our random color generator is a useful tool for designers, developers, and anyone who needs color inspiration. Each color is generated by randomly selecting red, green, and blue values between 0 and 255, giving you access to any of the 16.7 million possible colors. Copy colors in HEX for web design, RGB for programming, or HSL for easier color manipulation. Use the channel locking feature to explore variations — lock the hue to get different shades of the same color, or lock saturation to explore colors with similar vibrancy.
            </p>
          </div>

          {/* How It Works */}
          <div className="mb-10">
            <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-4">How Are Random Colors Generated?</h2>
            <p className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed mb-3">
              Colors on screens are defined in the RGB color model: three independent channels — Red, Green, and Blue — each ranging from 0 to 255. A fully random color is generated by independently sampling each channel: <code className="font-mono bg-gray-100 dark:bg-gray-800 px-1 rounded text-violet-700 dark:text-violet-400">r = Math.floor(Math.random() * 256)</code>, and the same for g and b. Combining three independent 8-bit values gives 256³ = 16,777,216 possible colors, which is every color that a standard display can render. The resulting RGB triplet is then converted to a 6-digit hexadecimal code (HEX) and to HSL (Hue, Saturation, Lightness) for use in different contexts.
            </p>
            <p className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed mb-3">
              The channel locking feature gives designers partial control over randomness. Locking the Hue channel fixes the color family and randomizes only how bright and vivid the color is — great for exploring shades of a chosen color. Locking Saturation keeps the vividness constant while varying the hue and lightness — useful when you need colors that all have the same level of visual intensity. Locking Lightness produces colors of a consistent brightness, which is especially valuable for accessibility work where maintaining sufficient contrast against backgrounds is important.
            </p>
            <p className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed">
              The HEX format (e.g. #A3F2B1) is the standard for web design and CSS. The RGB format (e.g. rgb(163, 242, 177)) is widely used in programming and image editing. The HSL format (e.g. hsl(131, 82%, 79%)) is often the most intuitive for designers because it separates the perceptual properties of the color — what color it is, how vivid it is, and how light or dark it is — into three independently adjustable values.
            </p>
          </div>

          {/* Worked Example */}
          <div className="rounded-2xl bg-gray-50 dark:bg-gray-900/50 border border-gray-100 dark:border-gray-800 px-6 py-5 mb-10">
            <h2 className="text-lg font-bold text-gray-900 dark:text-white mb-3">Worked Example: Designer Color Palette Discovery</h2>
            <p className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed mb-3">
              A web designer is starting a new brand identity project and needs a color palette. Rather than beginning with a predetermined color family and risk anchoring to the obvious choice, she uses the random color generator to explore the full 16.7 million color space. She generates colors rapidly using the Space bar, watching the large swatch update. When she spots a color that triggers an interesting reaction — a muted teal around #4A9B8E — she copies the HEX value and pauses.
            </p>
            <p className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed mb-3">
              She then locks the Hue channel (fixing the color family to teal) and generates 10 more colors to explore variations in saturation and lightness. This produces a range from nearly white pastels to deep jewel tones — all within the same hue family. She selects three that work together at different brightness levels, giving her a monochromatic accent palette. The palette generation button then creates 5 fully random colors she uses to identify complementary accent colors.
            </p>
            <p className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed">
              Other use cases: a game developer generates random colors for procedurally generated world environments; a data visualisation engineer uses the tool to quickly produce distinct colors for chart series; a generative art creator uses random HEX codes as inputs to an algorithm; a teacher uses random color generation to demonstrate RGB color mixing to students; an interior designer generates random accent colors to break out of habitual choices and find unexpected combinations that work.
            </p>
          </div>

          {/* Key Factors */}
          <div className="mb-10">
            <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-4">Key Factors in Random Color Generation</h2>
            <ul className="space-y-3">
              <li className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed">
                <strong className="text-gray-900 dark:text-white">Color space and channel independence</strong> — RGB colors are generated by sampling three independent channels. Because each channel is sampled independently, the full 16.7 million color space is accessible with perfectly equal probability for every possible color — from pure white (#FFFFFF) to pure black (#000000) and every color in between.
              </li>
              <li className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed">
                <strong className="text-gray-900 dark:text-white">HSL channel locking</strong> — Locking the Hue channel restricts generation to a single color family. Locking Saturation produces colors of consistent vividness. Locking Lightness produces colors of consistent brightness. Locking two channels simultaneously explores the full range of the unlocked channel, which is powerful for generating accessible, harmonious color sets.
              </li>
              <li className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed">
                <strong className="text-gray-900 dark:text-white">HEX vs RGB vs HSL format</strong> — HEX is the standard for CSS and web design. RGB is standard in most image editors and programming libraries. HSL is the most intuitive for manual colour adjustment. This tool provides all three simultaneously so you can copy whichever format your workflow requires.
              </li>
              <li className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed">
                <strong className="text-gray-900 dark:text-white">Palette generation</strong> — Generating 5 colors simultaneously provides a wider exploration canvas than single-color generation. Viewing multiple colors together allows you to immediately assess how they interact — whether they clash, complement, or form a cohesive palette — in a way that sequential single-color generation does not.
              </li>
              <li className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed">
                <strong className="text-gray-900 dark:text-white">Color history</strong> — The scrollable history of recent colors means you never permanently lose a color you generated earlier in a session. If an interesting color scrolls out of view while you continue exploring, the history lets you scroll back and retrieve it without starting over.
              </li>
            </ul>
          </div>

          <div className="pb-10">
            <FAQ questions={faqs} />
          </div>

          <div className="pb-6">
            <AdBanner slot="8888888880" />
          </div>
        </div>
      </section>

      <Footer />
    </>
  )
}
