import type { Metadata } from 'next'
import ToolHeader from '@/components/ToolHeader'
import RandomNumberWrapper from '@/components/RandomNumberWrapper'
import AdBanner from '@/components/AdBanner'
import FAQ from '@/components/FAQ'
import type { FaqItem } from '@/components/FAQ'
import Footer from '@/components/Footer'

export const metadata: Metadata = {
  title: 'Random Number Generator — Generate Random Numbers',
  description:
    'Generate random numbers instantly between any range. Free random number generator with multiple numbers, unique mode, decimals and quick presets. No signup.',
  alternates: { canonical: 'https://randomnumbergenerator.app' },
  robots: { index: true, follow: true },
}

const faqs: FaqItem[] = [
  {
    q: 'How do I generate a random number?',
    a: 'Simply enter a minimum and maximum value, then click GENERATE or press Space or Enter. Your random number appears instantly. You can also use the quick preset buttons for common ranges like 1–10, 1–100, or 1–1000.',
  },
  {
    q: 'Is this random number generator truly random?',
    a: "Our random number generator uses JavaScript's Math.random() function, which produces pseudo-random numbers. These are statistically indistinguishable from truly random numbers for virtually all everyday purposes — games, giveaways, decisions, and sampling. For cryptographic use, our password generator uses crypto.getRandomValues() instead.",
  },
  {
    q: 'Can I generate multiple random numbers at once?',
    a: 'Yes. Click "More options" to expand advanced settings, then increase "How many numbers" up to 1000. You can also enable "Unique numbers only" to ensure no repeats, choose your sort order, and exclude specific numbers.',
  },
  {
    q: 'What is the difference between random and pseudo-random?',
    a: 'True randomness comes from physical phenomena like radioactive decay. Pseudo-random numbers are generated by a mathematical algorithm seeded with an unpredictable value (like the current time). For most purposes they are equivalent. This generator uses pseudo-random numbers which are perfectly suitable for games, statistics, giveaways, and general use.',
  },
  {
    q: 'Is randomnumbergenerator.app completely free?',
    a: 'Yes, 100% free. All tools on randomnumbergenerator.app — including the random number generator, coin flip, dice roller, password generator, name picker, and all others — are free to use with no signup, no account, and no limits.',
  },
]

const faqSchema = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: faqs.map(f => ({ '@type': 'Question', name: f.q, acceptedAnswer: { '@type': 'Answer', text: f.a } })),
}

const webAppSchema = {
  '@context': 'https://schema.org',
  '@type': 'WebApplication',
  name: 'Random Number Generator',
  url: 'https://randomnumbergenerator.app',
  description: 'Free random number generator with range control, multiple numbers, unique mode, decimal support and history.',
  applicationCategory: 'UtilitiesApplication',
  operatingSystem: 'Any',
  offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
}

const howToSchema = {
  '@context': 'https://schema.org',
  '@type': 'HowTo',
  name: 'How to Generate a Random Number',
  step: [
    { '@type': 'HowToStep', name: 'Set your range', text: 'Enter a minimum and maximum value. The default range is 1 to 100, but you can use any numbers including negatives and decimals.' },
    { '@type': 'HowToStep', name: 'Click GENERATE', text: 'Press the GENERATE button, or use Space/Enter on your keyboard. Your random number appears instantly.' },
    { '@type': 'HowToStep', name: 'Customize with advanced options', text: 'Click "More options" to generate multiple numbers, enable unique mode, set decimal places, or exclude specific numbers.' },
  ],
}

const trustSignals = ['🎲 Truly Random', '⚡ Instant', '🔒 Private', '✓ Free']

export default function Home() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema).replace(/</g, '\\u003c') }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(webAppSchema).replace(/</g, '\\u003c') }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(howToSchema).replace(/</g, '\\u003c') }} />

      {/* Hero */}
      <section className="relative bg-cover bg-center bg-no-repeat" style={{ backgroundImage: "url('/herobgrng.webp')" }}>
        <div className="absolute inset-0 bg-black/60" />
        <div className="relative z-10 pb-10">
          <ToolHeader />
          <div className="text-center text-white px-4 py-8">
            <h1 className="text-3xl sm:text-4xl lg:text-5xl font-bold mb-3 leading-tight">
              Free Random Number Generator
            </h1>
            <p className="text-lg sm:text-xl text-white/80 mb-6 max-w-2xl mx-auto">
              Generate random numbers instantly between any range. No signup, completely free. Also try our coin flip, dice roller, name picker, and more random tools.
            </p>
            <div className="flex flex-wrap justify-center gap-3 text-sm">
              {trustSignals.map(t => (
                <span key={t} className="bg-white/20 backdrop-blur-sm rounded-full px-4 py-1.5 text-white font-medium">{t}</span>
              ))}
            </div>
          </div>

          <div className="max-w-4xl mx-auto px-4 mb-4">
            <AdBanner slot="1111111111" />
          </div>

          <div className="max-w-4xl mx-auto px-4">
            <div className="bg-white/90 dark:bg-gray-900/90 backdrop-blur-sm shadow-2xl rounded-2xl overflow-hidden">
              <RandomNumberWrapper />
            </div>
          </div>
        </div>
        <div className="absolute bottom-0 inset-x-0 h-24 bg-gradient-to-t from-white dark:from-[#0f172a] to-transparent pointer-events-none" />
      </section>

      {/* Below hero */}
      <section className="bg-white dark:bg-[#0f172a] pt-6">
        <div className="max-w-4xl mx-auto px-4 sm:px-6">
          <div className="pb-4">
            <AdBanner slot="2222222222" />
          </div>

          <div className="grid grid-cols-2 gap-3 sm:grid-cols-4 mb-10">
            {[
              { icon: '🎲', label: 'Truly Random', sub: 'Powered by Math.random()' },
              { icon: '⚡', label: 'Instant', sub: 'Results in milliseconds' },
              { icon: '🔒', label: 'Private', sub: 'Runs entirely in your browser' },
              { icon: '✓', label: 'Free', sub: 'No signup, no limits' },
            ].map(t => (
              <div key={t.label} className="flex flex-col items-center rounded-xl border border-gray-100 dark:border-gray-800 bg-white dark:bg-[#1e293b] p-4 text-center shadow-sm">
                <span className="text-2xl mb-1">{t.icon}</span>
                <span className="text-sm font-semibold text-gray-800 dark:text-[#e2e8f0]">{t.label}</span>
                <span className="text-xs text-gray-400 mt-0.5">{t.sub}</span>
              </div>
            ))}
          </div>

          <div className="rounded-2xl bg-violet-50 dark:bg-violet-950/30 border border-violet-100 dark:border-violet-900/50 px-6 py-5 mb-10">
            <h2 className="text-base font-bold text-violet-900 dark:text-violet-300 mb-2">
              What is a random number generator?
            </h2>
            <p className="text-sm text-violet-800 dark:text-violet-400 leading-relaxed">
              A random number generator (RNG) produces numbers with no predictable pattern. Our free random number generator lets you generate random numbers instantly between any range — from simple 1 to 10 picks to large datasets of 1000 unique numbers. Use it for games, giveaways, sampling, decisions, lottery number selection, or any situation where you need a fair, unbiased random number. All generation happens in your browser — your inputs never leave your device.
            </p>
          </div>

          {/* How It Works */}
          <div className="mb-10">
            <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-4">How Does a Random Number Generator Work?</h2>
            <p className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed mb-3">
              JavaScript&apos;s <code className="font-mono bg-gray-100 dark:bg-gray-800 px-1 rounded text-violet-700 dark:text-violet-400">Math.random()</code> function produces a floating-point number between 0 (inclusive) and 1 (exclusive) using a pseudo-random number generator algorithm — typically a variant of xorshift128+ in modern browsers like Chrome and Firefox. To generate a whole number within your chosen range, the tool applies the formula <code className="font-mono bg-gray-100 dark:bg-gray-800 px-1 rounded text-violet-700 dark:text-violet-400">Math.floor(Math.random() * (max - min + 1)) + min</code>, which scales and shifts the 0–1 output precisely into your specified range.
            </p>
            <p className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed mb-3">
              The term &quot;pseudo-random&quot; means the numbers are produced by a deterministic mathematical algorithm rather than a physical entropy source such as radioactive decay or atmospheric noise. The algorithm is seeded with an unpredictable value — typically derived from the system clock combined with hardware timing events — making each sequence appear statistically random. For games, giveaways, statistical sampling, classroom selection, and the vast majority of everyday tasks, pseudo-random numbers are completely indistinguishable from truly random ones in practice.
            </p>
            <p className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed">
              All generation happens entirely in your browser with zero server involvement. Results appear in under a millisecond because no network round-trip is required. Critically, each result is also independent: past outputs have absolutely no influence on future ones. This mirrors a fair physical die — rolling a 6 does not change the probability of rolling a 6 on the next throw. That statistical independence is what makes this tool reliable for any application requiring genuine, unbiased fairness.
            </p>
          </div>

          {/* Worked Example */}
          <div className="rounded-2xl bg-gray-50 dark:bg-gray-900/50 border border-gray-100 dark:border-gray-800 px-6 py-5 mb-10">
            <h2 className="text-lg font-bold text-gray-900 dark:text-white mb-3">Worked Example: Classroom Student Selection</h2>
            <p className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed mb-3">
              A teacher needs to randomly select students for 30-second presentations. Her class has 28 students numbered 1–28 on her seating chart. She sets the minimum to 1 and the maximum to 28, enables &quot;Unique numbers only&quot; with a count of 28, and clicks Generate. The tool instantly produces a randomized sequence of every number from 1 to 28 — the entire class in a random order with no repeats.
            </p>
            <p className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed mb-3">
              The process is fully transparent: every student can see the generator and verify that the selection is genuinely random. There is no favoritism, no unconscious bias toward students near the front row, and no memory of who was called on last week. The fairness is mathematically guaranteed — not merely asserted — and can be demonstrated to the whole class in seconds.
            </p>
            <p className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed">
              Other practical uses: a raffle organizer selects 5 winning ticket numbers from 1–500 for a charity prize draw; a researcher generates 100 unique participant IDs for a blind study; a board game designer creates randomized map terrain values using decimal output; a developer populates a test database with realistic random prices between 9.99 and 999.99. In every case the guarantee is the same — a statistically fair, unbiased, and instantly verifiable result produced entirely within the browser.
            </p>
          </div>

          {/* Key Factors */}
          <div className="mb-10">
            <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-4">Key Factors in Random Number Generation</h2>
            <ul className="space-y-3">
              <li className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed">
                <strong className="text-gray-900 dark:text-white">Range selection</strong> — The minimum and maximum values define the complete pool of possible outputs. A narrower range concentrates probability on fewer values; a wider range spreads it evenly across more. Both negative numbers and decimal boundaries are fully supported, enabling use cases from temperature simulation to financial modelling.
              </li>
              <li className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed">
                <strong className="text-gray-900 dark:text-white">Integer vs decimal output</strong> — Whole numbers suit most everyday uses: picking winners, selecting list items, simulating dice. Decimal output with up to 10 decimal places suits scientific applications, probability simulations, or any task requiring continuous random values rather than discrete whole numbers.
              </li>
              <li className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed">
                <strong className="text-gray-900 dark:text-white">Unique numbers only</strong> — When generating multiple numbers, enabling this mode ensures no value appears more than once in the output. It is essential for prize draws, generating shuffled permutations, or any scenario where duplicates would be unfair or statistically invalid.
              </li>
              <li className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed">
                <strong className="text-gray-900 dark:text-white">Generating multiple numbers at once</strong> — Producing up to 1,000 numbers simultaneously suits bulk tasks: building random datasets, shuffling ordered lists, running Monte Carlo simulations, or creating large volumes of test data without tedious manual repetition.
              </li>
              <li className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed">
                <strong className="text-gray-900 dark:text-white">Pseudorandom vs cryptographic randomness</strong> — Math.random() is ideal for games, decisions, and general-purpose sampling. For security-critical work such as generating passwords or encryption keys, this site switches to crypto.getRandomValues() — drawing from the operating system&apos;s hardware-backed entropy pool for output that is genuinely and verifiably unpredictable.
              </li>
            </ul>
          </div>

          <div className="pb-10">
            <FAQ questions={faqs} />
          </div>

          <div className="pb-6">
            <AdBanner slot="3333333333" />
          </div>
        </div>
      </section>

      <Footer />
    </>
  )
}
