import type { Metadata } from 'next'
import ToolHeader from '@/components/ToolHeader'
import RandomNumberWrapper from '@/components/RandomNumberWrapper'
import AdBanner from '@/components/AdBanner'
import FAQ from '@/components/FAQ'
import type { FaqItem } from '@/components/FAQ'
import Footer from '@/components/Footer'

export const metadata: Metadata = {
  title: 'Random Number Generator — Generate Random Numbers',
  description:
    'Generate random numbers instantly between any range. Free random number generator with multiple numbers, unique mode, decimals, and quick presets. No signup required.',
  alternates: { canonical: 'https://randomnumbergenerator.app' },
  robots: { index: true, follow: true },
}

const faqs: FaqItem[] = [
  {
    q: 'How do I generate a random number?',
    a: 'Simply enter a minimum and maximum value, then click GENERATE or press Space or Enter. Your random number appears instantly. You can also use the quick preset buttons for common ranges like 1–10, 1–100, or 1–1000.',
  },
  {
    q: 'Is this random number generator truly random?',
    a: "Our random number generator uses JavaScript's Math.random() function, which produces pseudo-random numbers. These are statistically indistinguishable from truly random numbers for virtually all everyday purposes — games, giveaways, decisions, and sampling. For cryptographic use, our password generator uses crypto.getRandomValues() instead.",
  },
  {
    q: 'Can I generate multiple random numbers at once?',
    a: 'Yes. Click "More options" to expand advanced settings, then increase "How many numbers" up to 1000. You can also enable "Unique numbers only" to ensure no repeats, choose your sort order, and exclude specific numbers.',
  },
  {
    q: 'What is the difference between random and pseudo-random?',
    a: 'True randomness comes from physical phenomena like radioactive decay. Pseudo-random numbers are generated by a mathematical algorithm seeded with an unpredictable value (like the current time). For most purposes they are equivalent. This generator uses pseudo-random numbers which are perfectly suitable for games, statistics, giveaways, and general use.',
  },
  {
    q: 'Is randomnumbergenerator.app completely free?',
    a: 'Yes, 100% free. All tools on randomnumbergenerator.app — including the random number generator, coin flip, dice roller, password generator, name picker, and all others — are free to use with no signup, no account, and no limits.',
  },
]

const faqSchema = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: faqs.map(f => ({ '@type': 'Question', name: f.q, acceptedAnswer: { '@type': 'Answer', text: f.a } })),
}

const webAppSchema = {
  '@context': 'https://schema.org',
  '@type': 'WebApplication',
  name: 'Random Number Generator',
  url: 'https://randomnumbergenerator.app',
  description: 'Free random number generator with range control, multiple numbers, unique mode, decimal support and history.',
  applicationCategory: 'UtilitiesApplication',
  operatingSystem: 'Any',
  offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
}

const howToSchema = {
  '@context': 'https://schema.org',
  '@type': 'HowTo',
  name: 'How to Generate a Random Number',
  step: [
    { '@type': 'HowToStep', name: 'Set your range', text: 'Enter a minimum and maximum value. The default range is 1 to 100, but you can use any numbers including negatives and decimals.' },
    { '@type': 'HowToStep', name: 'Click GENERATE', text: 'Press the GENERATE button, or use Space/Enter on your keyboard. Your random number appears instantly.' },
    { '@type': 'HowToStep', name: 'Customize with advanced options', text: 'Click "More options" to generate multiple numbers, enable unique mode, set decimal places, or exclude specific numbers.' },
  ],
}

const trustSignals = ['🎲 Truly Random', '⚡ Instant', '🔒 Private', '✓ Free']

export default function Home() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema).replace(/</g, '\\u003c') }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(webAppSchema).replace(/</g, '\\u003c') }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(howToSchema).replace(/</g, '\\u003c') }} />

      {/* Hero */}
      <section className="relative bg-cover bg-center bg-no-repeat" style={{ backgroundImage: "url('/herobgrng.webp')" }}>
        <div className="absolute inset-0 bg-black/60" />
        <div className="relative z-10 pb-10">
          <ToolHeader />
          <div className="text-center text-white px-4 py-8">
            <h1 className="text-3xl sm:text-4xl lg:text-5xl font-bold mb-3 leading-tight">
              Free Random Number Generator
            </h1>
            <p className="text-lg sm:text-xl text-white/80 mb-6 max-w-2xl mx-auto">
              Generate random numbers instantly between any range. No signup, completely free. Also try our coin flip, dice roller, name picker, and more random tools.
            </p>
            <div className="flex flex-wrap justify-center gap-3 text-sm">
              {trustSignals.map(t => (
                <span key={t} className="bg-white/20 backdrop-blur-sm rounded-full px-4 py-1.5 text-white font-medium">{t}</span>
              ))}
            </div>
          </div>

          <div className="max-w-4xl mx-auto px-4 mb-4">
            <AdBanner slot="1111111111" />
          </div>

          <div className="max-w-4xl mx-auto px-4">
            <div className="bg-white/90 dark:bg-gray-900/90 backdrop-blur-sm shadow-2xl rounded-2xl overflow-hidden">
              <RandomNumberWrapper />
            </div>
          </div>
        </div>
        <div className="absolute bottom-0 inset-x-0 h-24 bg-gradient-to-t from-white dark:from-[#0f172a] to-transparent pointer-events-none" />
      </section>

      {/* Below hero */}
      <section className="bg-white dark:bg-[#0f172a] pt-6">
        <div className="max-w-4xl mx-auto px-4 sm:px-6">
          <div className="pb-4">
            <AdBanner slot="2222222222" />
          </div>

          <div className="grid grid-cols-2 gap-3 sm:grid-cols-4 mb-10">
            {[
              { icon: '🎲', label: 'Truly Random', sub: 'Powered by Math.random()' },
              { icon: '⚡', label: 'Instant', sub: 'Results in milliseconds' },
              { icon: '🔒', label: 'Private', sub: 'Runs entirely in your browser' },
              { icon: '✓', label: 'Free', sub: 'No signup, no limits' },
            ].map(t => (
              <div key={t.label} className="flex flex-col items-center rounded-xl border border-gray-100 dark:border-gray-800 bg-white dark:bg-[#1e293b] p-4 text-center shadow-sm">
                <span className="text-2xl mb-1">{t.icon}</span>
                <span className="text-sm font-semibold text-gray-800 dark:text-[#e2e8f0]">{t.label}</span>
                <span className="text-xs text-gray-400 mt-0.5">{t.sub}</span>
              </div>
            ))}
          </div>

          <div className="rounded-2xl bg-violet-50 dark:bg-violet-950/30 border border-violet-100 dark:border-violet-900/50 px-6 py-5 mb-10">
            <h2 className="text-base font-bold text-violet-900 dark:text-violet-300 mb-2">
              What is a random number generator?
            </h2>
            <p className="text-sm text-violet-800 dark:text-violet-400 leading-relaxed">
              A random number generator (RNG) produces numbers with no predictable pattern. Our free random number generator lets you generate random numbers instantly between any range — from simple 1 to 10 picks to large datasets of 1000 unique numbers. Use it for games, giveaways, sampling, decisions, lottery number selection, or any situation where you need a fair, unbiased random number. All generation happens in your browser — your inputs never leave your device.
            </p>
          </div>

          <div className="pb-10">
            <FAQ questions={faqs} />
          </div>

          <div className="pb-6">
            <AdBanner slot="3333333333" />
          </div>
        </div>
      </section>

      <Footer />
    </>
  )
}
